// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD21HilhQBdpBFXNcuuEEdU01Wp8bH9sm4',
    appId: '1:415880282002:web:37f17eb99f54e319080b4b',
    messagingSenderId: '415880282002',
    projectId: 'wordle-services',
    authDomain: 'wordle-services.firebaseapp.com',
    storageBucket: 'wordle-services.firebasestorage.app',
    measurementId: 'G-GBBNPYLNVW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaHzKnf8Z9BeoEDPMbaxp_yU3NhNUY-Vs',
    appId: '1:415880282002:android:d99b5c82fdb826ee080b4b',
    messagingSenderId: '415880282002',
    projectId: 'wordle-services',
    storageBucket: 'wordle-services.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkoEeaMhB5kkWxTLLz5Nw1inv0GDNEMQw',
    appId: '1:415880282002:ios:4045286a2b4d30ad080b4b',
    messagingSenderId: '415880282002',
    projectId: 'wordle-services',
    storageBucket: 'wordle-services.firebasestorage.app',
    iosBundleId: 'com.example.otpBoxes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkoEeaMhB5kkWxTLLz5Nw1inv0GDNEMQw',
    appId: '1:415880282002:ios:4045286a2b4d30ad080b4b',
    messagingSenderId: '415880282002',
    projectId: 'wordle-services',
    storageBucket: 'wordle-services.firebasestorage.app',
    iosBundleId: 'com.example.otpBoxes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD21HilhQBdpBFXNcuuEEdU01Wp8bH9sm4',
    appId: '1:415880282002:web:dd02c1a6e5868887080b4b',
    messagingSenderId: '415880282002',
    projectId: 'wordle-services',
    authDomain: 'wordle-services.firebaseapp.com',
    storageBucket: 'wordle-services.firebasestorage.app',
    measurementId: 'G-B3NMSW8TJ5',
  );
}
