// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      // case TargetPlatform.windows:
      //   return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcEteO50mLq9audVJfj9jPEf0VNBw-m6U',
    appId: '1:873429164398:web:404c6fe33e1c292f79617f',
    messagingSenderId: '873429164398',
    projectId: 'fir-auth-fa4df',
    authDomain: 'fir-auth-fa4df.firebaseapp.com',
    storageBucket: 'fir-auth-fa4df.firebasestorage.app',
    measurementId: 'G-6RF1RNGZPB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALbrdQoFup3SR4pEjyTOJMIsQ7zE22c34',
    appId: '1:873429164398:android:abd281341f95419779617f',
    messagingSenderId: '873429164398',
    projectId: 'fir-auth-fa4df',
    storageBucket: 'fir-auth-fa4df.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHKwiU10lyg_F29bMtdJFlvRUDZdoc5co',
    appId: '1:873429164398:ios:8fb2076993b8b25b79617f',
    messagingSenderId: '873429164398',
    projectId: 'fir-auth-fa4df',
    storageBucket: 'fir-auth-fa4df.firebasestorage.app',
    iosBundleId: 'com.example.otpBoxes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHKwiU10lyg_F29bMtdJFlvRUDZdoc5co',
    appId: '1:873429164398:ios:8fb2076993b8b25b79617f',
    messagingSenderId: '873429164398',
    projectId: 'fir-auth-fa4df',
    storageBucket: 'fir-auth-fa4df.firebasestorage.app',
    iosBundleId: 'com.example.otpBoxes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcEteO50mLq9audVJfj9jPEf0VNBw-m6U',
    appId: '1:873429164398:web:8a39bbe91c9945d979617f',
    messagingSenderId: '873429164398',
    projectId: 'fir-auth-fa4df',
    authDomain: 'fir-auth-fa4df.firebaseapp.com',
    storageBucket: 'fir-auth-fa4df.firebasestorage.app',
    measurementId: 'G-9MCW26S2X0',
  );

}